name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release-github:
    name: Create GitHub release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Apply version
        run: |
          version=$(git log --pretty=format:%s -n 1 | awk -F' ' '{print $2}')

          if [[ "$version" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
            echo "APP_VERSION=$version" >> $GITHUB_ENV
          else
            echo "Parsed version: $version"
            echo "Commit message: $(git log --pretty=format:%s -n 1)"
            exit 1
          fi

      - name: Create a release tag
        run: |
          git tag "$APP_VERSION"
          git push origin "refs/tags/$APP_VERSION"

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create $APP_VERSION \
          --title "$APP_VERSION" \
          --notes "Please refer to the [documentation](https://bidaro-open-source.github.io/changelog/)." \
          --latest

  release-docker:
    name: Create docker release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Apply version
        run: |
          version=$(git log --pretty=format:%s -n 1 | awk -F' ' '{print $2}')

          if [[ "$version" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
            echo "APP_VERSION=$version" >> $GITHUB_ENV
          else
            echo "Parsed version: $version"
            echo "Commit message: $(git log --pretty=format:%s -n 1)"
            exit 1
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/bidaro-migrator:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/bidaro-migrator:${{ env.APP_VERSION }}
